# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ":9000"
    volumes:
      - .:/app/
    restart: unless-stopped
  server:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app/
    restart: unless-stopped
  db:
    build:
      dockerfile: docker/database/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - \db\mariadata
    secrets:
      - db_root_pass
      - db_pass

secrets:
  db_root_pass:
    file: ./docker/secrets/db_root_pass
  db_pass:
    file: ./docker/secrets/db_pass

volumes:
  dbvol:

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

